Adding/Deleting authorization and telemetry headers
microsoftgraph/msgraph-sdk-javascript pull request #351
Opened 2020-11-10 02:49 UTC by nikithauc

Fixes #265 and #344 

Problem 1 - #265 reports a CORs error which was caused because the SDK added telemetry headers only for every request that goes out. The redirected non-Graph endpoint complained about the unexpected SDK_Version header and caused a CORS error.
Solution for Problem 1 - This PR includes logic to check in the `TelemetryHandler` if the URL is a Graph URL and if yes process to add the telemetry headers. If the URL is a non Graph URL and the telemetry headers are present, then the headers are deleted.

Problem 2 - #344 @peombwa Thank you for helping me reproduce this issue! 
On redirection, the `RedirectionHandler` is currently setting the AuthorizationHeader to undefined instead of completely dropping the header key. 
The existing code worked fine in a node environment but failed when using ExpressJS. 

Solution for Problem 2 - This PR includes change in the `RedirectionHandler` to delete Authorization header key if present.

2020-11-10 12:51 UTC, baywet requested changes

2020-11-10 12:51 UTC, baywet commented on src/GraphRequestUtil.ts
> +	const urls = ["graph.microsoft.com", "graph.microsoft.us", "dod-graph.microsoft.us", "graph.microsoft.de", "microsoftgraph.chinacloudapi.cn"];
Set initialization instead and core-js requirement for older browsers?

2020-11-10 12:51 UTC, baywet commented on src/middleware/TelemetryHandler.ts
> +					if (typeof options !== "undefined") {
```suggestion
					if (options !== undefined) {
```

2020-11-11 01:23 UTC, zengin requested changes

2020-11-11 01:23 UTC, zengin commented on spec/middleware/TelemetryHandler.ts
> +			}
Please remove the try catch block.

2020-11-11 01:23 UTC, zengin commented on src/middleware/TelemetryHandler.ts
> +					}
I think you can call delete on the keys even if they don't exist. See [this example](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBDIKMjJHooWg-QTwLwAb0UJRKnAYyHyglQlE4zHZHIYzEgAH58px2IhpD9FABfADcwQQnD51UZzNA+ToWq8AF5QGyOYNuZBdQAiYhISAAOXNlt4wpKootoAAjAAGRUqxRqpnuALQeDMAAUGyZnAAlCruDBIApNb9mQBtS1uy0AXRVAfgQZD4cjzNjQA)
```suggestion
					delete context.options.headers[TelemetryHandler.CLIENT_REQUEST_ID_HEADER];
					delete context.options.headers[TelemetryHandler.SDK_VERSION_HEADER];
```

2020-11-11 01:23 UTC, zengin commented on src/middleware/RedirectHandler.ts
> +					if (!this.isRelativeURL(redirectUrl) && this.shouldDropAuthorizationHeader(response.url, redirectUrl) && context.options.headers[RedirectHandler.AUTHORIZATION_HEADER]) {
see the example I gave below on delete.

2020-11-11 12:28 UTC, baywet approved these changes
besides the comments @zengin already added, LGTM. Thanks for making the changes!

2020-11-11 15:04 UTC, MIchaelMainer reviewed
Oops, forgot to submit this yesterday

2020-11-11 20:46 UTC, zengin approved these changes

2020-11-11 21:16 UTC, baywet approved these changes

2020-11-11 23:43 UTC, MIchaelMainer approved these changes

2020-11-11 23:45 UTC, merged