Shows how to download photos with batching and prepare them for rendering in a browser
microsoftgraph/msgraph-sdk-javascript pull request #368
Opened 2020-12-31 08:47 UTC by plamber

## Summary
This example shows how to download multiple photos with batching and how to convert them in base64 for further rendering. Useful for people picker scenarios.

## Closing issues
Closes: #367

## Checklist

-   [x] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2020-12-31 13:21 UTC, baywet requested changes
Great addition! Thanks for putting it together so fast. I added a few minor comments for consistency and word use

2020-12-31 13:21 UTC, baywet commented on docs/content/Batching.md
> +### Download multiple profile photos with batching and prepare manipulate these for rendering in a browser
```suggestion
### Download multiple profile photos with batching and preprocess these for rendering in a browser 
```

2020-12-31 13:21 UTC, baywet commented on docs/content/Batching.md
> +        const _binToBlob = await this.b64toBlob((data),'img/jpg');
```suggestion
        const binToBlob = await this.b64toBlob((data),'img/jpg');
```

2020-12-31 13:21 UTC, baywet commented on docs/content/Batching.md
> +        const base64Result = await this.blobToBase64(_binToBlob);
```suggestion
        const base64Result = await this.blobToBase64(binToBlob);
```

2020-12-31 21:53 UTC, nikithauc submitted a review, later dismissed

2021-01-02 02:35 UTC, nikithauc approved these changes

2021-01-04 12:19 UTC, baywet approved these changes

2021-01-04 14:16 UTC, merged