Documentation - add links to JS samples
microsoftgraph/msgraph-sdk-javascript pull request #473
Opened 2021-06-14 22:53 UTC by nikithauc

Fixes #470

2021-06-14 23:38 UTC, MIchaelMainer approved these changes

2021-06-14 23:40 UTC, MIchaelMainer requested changes
The sendUsersMail image and link is a bit off. Should probably be in a section about typings.

Also, there are duplicate links to samples and tutorials at the bottom of the document. Perhaps that is a good thing, it is nice to find the links in the TOC.

2021-06-15 00:53 UTC, nikithauc commented
> The sendUsersMail image and link is a bit off. Should probably be in a section about typings.
> 
> Also, there are duplicate links to samples and tutorials at the bottom of the document. Perhaps that is a good thing, it is nice to find the links in the TOC.

@MIchaelMainer can you explain what should be the correction be for the sendUsersMail image and link? 

The duplicate links in the TOC and the samples sections are intentional.

2021-06-15 11:22 UTC, baywet commented on README.md
> +            - [Build Angular single-page apps with Microsoft Graph](https://docs.microsoft.com/en-us/graph/tutorials/angular)
nit: if you remove en-us from the links, people will get redirected to their language if it's available

2021-06-15 21:50 UTC, MIchaelMainer commented
@nikithauc The sendUsersMail image and link occur in the same section as that TOC/Navigation section. There should a section and description that describe what the image is and why the customer should follow it.

Perhaps something like:

## TypeScript

This client library is supported with typings that represent the objects in Microsoft Graph. We provide typing support for the [v1.0](https://github.com/microsoftgraph/msgraph-typescript-typings) and [beta](https://github.com/microsoftgraph/msgraph-beta-typescript-typings) models.

[![TypeScript demo](https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-javascript/master/types-demo.PNG)](https://github.com/microsoftgraph/msgraph-typescript-typings)

2021-06-17 22:59 UTC, nikithauc commented
> @nikithauc The sendUsersMail image and link occur in the same section as that TOC/Navigation section. There should a section and description that describe what the image is and why the customer should follow it.
> 
> Perhaps something like:
> 
> ## TypeScript
> This client library is supported with typings that represent the objects in Microsoft Graph. We provide typing support for the [v1.0](https://github.com/microsoftgraph/msgraph-typescript-typings) and [beta](https://github.com/microsoftgraph/msgraph-beta-typescript-typings) models.
> 
> [![TypeScript demo](https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-javascript/master/types-demo.PNG)](https://github.com/microsoftgraph/msgraph-typescript-typings)
Done!

2021-06-17 23:02 UTC, MIchaelMainer approved these changes

2021-06-18 04:34 UTC, merged