Introducing Kiota Authentication
microsoftgraph/msgraph-sdk-javascript pull request #590
Opened 2022-01-28 06:49 UTC by nikithauc

This PR is WIP.

- Tested a core `client.api("")` request using Kiota Authentication. 
- Removed the `Graph.IAuthenticationProvider` and modified code to align with `Kiota.IAuthenticationProvider` and `Kiota.IAccessTokenProvider`.
- Added a `SimpleAuthenticationProvider` as suggested by @sebastienlevert aligning with MGT SimpleProvider. We could move this to Kiota too. 
https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/ec1a5bf8cbe0f76f4aea9da8ad425b144f5c6572/packages/mgt-element/src/providers/SimpleProvider.ts#L19

2022-01-28 15:58 UTC, baywet requested changes
thanks for starting this! It's great to see things starting to line up! Lots of work ahead but it's starting to take shape! Two minor comments on my side.

2022-01-28 15:58 UTC, baywet commented on src/authentication/SimpleAuthentication/IAuthProviderCallback.ts
> +export interface AuthProviderCallback {
What's the value of this interface since we already have access token provider in kiota? (or will have soon at least)

2022-01-28 15:58 UTC, baywet commented on src/authentication/SimpleAuthentication/SimpleAccessTokenProvider.ts
> +    public getAuthorizationToken(): Promise<string> {
note, should probably be using the allowed host validator and check for https

2022-02-14 14:18 UTC, baywet commented on src/authentication/SimpleAuthentication/SimpleAccessTokenProvider.ts
> +		if (!url || !this.allowedHostsValidator.isUrlHostValid(url)) {
check for https

2022-02-14 14:22 UTC, baywet commented on src/GraphRequest.ts
> +		const requestInfo = new RequestInformation();
assuming we're manipulating a BaseBearerTokenAuthenticationProvider and this provides a property for the access token provider, you shouldn't have to instantiate a request information at all for arbitrary requests

2022-03-15 12:32 UTC, baywet requested changes

2022-03-15 12:32 UTC, baywet commented on src/middleware/AuthenticationHandler.ts
>  	 * @param {AuthenticationProvider} authenticationProvider - The authentication provider for the authentication handler
param name and description needs to be updated

2022-03-15 12:32 UTC, baywet commented on design/kiota-e2e.md
> +	authenticationTokenProvider: new AzureIdentityAuthenticationProvider(deviceCodeCredentials, scopes),
```suggestion
	authenticationProvider: new AzureIdentityAuthenticationProvider(deviceCodeCredentials, scopes),
```

2022-03-15 12:32 UTC, baywet commented on design/kiota-e2e.md
> +npm install @microsoft/msgraph-sdk-javascript-types --save-dev
are we still going to chip the type separately at this point?

2022-03-15 12:32 UTC, baywet commented on design/kiota-e2e.md
> +	authenticationTokenProvider: new AzureIdentityAuthenticationProvider(deviceCodeCredentials, scopes),
```suggestion
	authenticationProvider: new AzureIdentityAuthenticationProvider(deviceCodeCredentials, scopes),
```

2022-03-18 18:05 UTC, baywet commented
isn't this one superseded by #712 at this point? lots of duplicate changes

2022-03-23 05:01 UTC, nikithauc commented
The changes here are contains in #712

2022-03-23 05:01 UTC, closed without merging